### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Mored1984** [Dantttt/YuzuUpdater#4]
I want to use this, but How??

Current version yuzu v**1.0.1980** (msvc)(x64) want to  auto update to yuzu v**1.0.2183** (mingw)(x64)

Note emulator directory **C:\Program Files\Emulators\yuzu**

**Comment by Mored1984** [comment]
![image](https://user-images.githubusercontent.com/5413459/43507557-25e82d56-9576-11e8-8e06-fa310fb3cc91.png)


![image](https://user-images.githubusercontent.com/5413459/43507591-37debd86-9576-11e8-930b-cce0f35c0b99.png)


No update

**Comment by Dantttt** [comment]
In your folder you are missing the file SharpCompress.dll content into the packet installation
